// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Neuralia",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Neuralia",
            targets: ["AppModule"],
            bundleIdentifier: "Jnx03.mrc.Neura",
            teamIdentifier: "SGXTQ97U4A",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            sources: ["ContentView.swift", "CreditsView.swift", "DialogSystem.swift", "DialogSystemPreview.swift", "FeatureTestingData.swift", "FeatureTestingPreview.swift", "FeatureTestingView.swift", "GlobalSettings.swift", "ImageTrainingView.swift", "LoadingView.swift", "MainMenu.swift", "NeuraApp.swift", "PointerFX.swift", "ResponsiveLayout.swift", "SettingsView.swift", "SharedUISupport.swift", "Story/Chapter1/Chapter1Story.swift", "Story/Chapter2/Chapter2Story.swift", "Story/Chapter3/Chapter3Story.swift", "Story/StoryChapterHubView.swift", "Story/StoryChapterPlayerView.swift", "Story/StoryScriptModels.swift", "StoryGalleryMuseumView.swift", "StoryProgressStore.swift"],
            resources: [
                .process("Assets.xcassets")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
