// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Neuralia",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Neuralia",
            targets: ["AppModule"],
            bundleIdentifier: "Jnx03.mrc.Neura",
            teamIdentifier: "SGXTQ97U4A",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            sources: ["App/ContentView.swift", "Features/CreditsView.swift", "Features/DialogSystem.swift", "Previews/DialogSystemPreview.swift", "Testing/FeatureTestingData.swift", "Previews/FeatureTestingPreview.swift", "Testing/FeatureTestingView.swift", "Core/GlobalSettings.swift", "Features/ImageTrainingView.swift", "Features/LoadingView.swift", "Features/MainMenu.swift", "App/NeuraApp.swift", "Core/PointerFX.swift", "Core/ResponsiveLayout.swift", "Features/SettingsView.swift", "Core/SharedUISupport.swift", "Story/Chapter1/Chapter1Story.swift", "Story/Chapter2/Chapter2Story.swift", "Story/Chapter3/Chapter3Story.swift", "Story/StoryChapterHubView.swift", "Story/StoryChapterPlayerView.swift", "Story/StoryScriptModels.swift", "Features/StoryGalleryMuseumView.swift", "State/StoryProgressStore.swift"],
            resources: [
                .process("Assets.xcassets")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
